### ISSUE TITLE
[Engine] Serializer Todo List

### ISSUE THREAD

**Issue by michaelsakharov** [michaelsakharov/Prowl#74]
- [x] IList
- [x] Array - Seems to be handling them pretty well now
- [x] IDictionary
- [x] String
- [x] Bool
- [x] Byte
- [x] sByte
- [x] Int16
- [x] Int32
- [x] Int64
- [x] UInt16
- [x] UInt32
- [x] UInt64
- [x] Float
- [x] Double
- [x] Decimal
- [x] Enum - Serialized as Int32
- [x] DateTime - Serialized as Int64
- [x] Byte[]
- [x] Guid - Serialized as String

**Comment by michaelsakharov** [comment]
Im sure theres more i've missed but this covers most cases
